### PR TITLE
search

### PR DESCRIPTION
**Pull request by mhant**
adding search bar
optimizing icons
changing current location icon
changing access token to one with places permission

### CODE REVIEW

**Comment by mhant** [comment]
UI for icon optimization to make room for search (default mobile phone)
new_ui_search

**Comment by mhant** [comment]
new current location using google location dot (small iPhone 5/SE)
new_current_location

**Comment by spledgoldstein** [comment]
special zoom for restaurants should be 19.
If possible try to clear the search box when you click in it.

**Review by spledgoldstein — APPROVED** [review]
Yes, all looks good. well done. OK to merge.

**Pull request merged**
